name: deploy-stg

on:
  push:
    tags:
      - "v*"

defaults:
  run:
    shell: bash

jobs:
  staging:
    runs-on: ubuntu-latest

    environment:
      name: stg
      url: https://stg.networkbasedsolutions.com

    env:
      TAG: ${{ github.ref_name }}
      SFTP_HOST: ${{ vars.SFTP_HOST }}
      SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
      SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
      SFTP_PATH: ${{ vars.SFTP_PATH }}

    steps:
      - name: Checkout Project
        uses: actions/checkout@v6

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          cache: true
          deno-version-file: .tool-versions

      - name: Deploy to Staging
        run: deno task deploy

      - name: Archive Artifacts
        uses: actions/upload-artifact@v6
        with:
          if-no-files-found: error
          name: nbs-stg-${{ env.TAG }}
          path: dist/
